### ISSUE TITLE
ImportError: This module is deprecated.  Use tf.nn.rnn_* instead.

### ISSUE THREAD

**Issue by Chin-I** [tencia/stocks_rnn#4]
Can anyone provide a new version code?

(tensorflow) dhcp-v097-009:stocks_rnn-master Gene$ python train_stock_lstm.py 
Traceback (most recent call last):
  File "train_stock_lstm.py", line 13, in <module>
    from tensorflow.models.rnn import rnn
  File "/Users/Gene/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/models/rnn/rnn.py", line 21, in <module>
    raise ImportError("This module is deprecated.  Use tf.nn.rnn_* instead.")
ImportError: This module is deprecated.  Use tf.nn.rnn_* instead.

**Comment by shawnliucmcm** [comment]
Replace tensorflow.models.rnn with tensorflow.python.ops, and it should work.
